# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  jestTesting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.16.3]

    env:
      ENVIROMENT: test
      REDIS_HOST: redis-13073.c10.us-east-1-4.ec2.cloud.redislabs.com
      CONFIG_BCRYPT_SALT_ROUNDS: 20
      DATABASE_PROVIDER: mysql
      TESTDATABASE_URL: mysql://developer:testing@localhost:3800/some_test
      JWT_SECRET_ACCESS: asdasasdqwe13
      JWT_SECRET_REFRESH: refresh
      TWILIO_ACCOUNT_SID: AC7b218b46000c5a3f092ab62abe598f7a
      TWILIO_ACCOUNT_TOKEN: 65963e7203b05b64dcddbfd2a2f0b3c6
      TWILIO_SMS_CELLPHONE_NUMBER: +12058906313
      REDIS_PASSWORD: aWEkwtTXb3TNCfLsnqrvp49yw1n7iG78
      REDIS_PORT: 13073

    steps:
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it

      - # ... some steps before set-up MySQL ...
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3800 # Optional, default value is 3306. The port of host
          container port: 3307 # Optional, default value is 3306. The port of container
          character set server: utf8 # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: utf8_general_ci # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mysql database: some_test # Optional, default value is "test". The specified database which will be create
          mysql root password: test # Required if "mysql user" is empty, default is empty. The root superuser password
          mysql user: developer # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: testing # Required if "mysql user" exists. The password for the "mysql user"

      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
